### ISSUE TITLE
flop calculation 

### ISSUE THREAD

**Issue by Akash08naik** [EleutherAI/cookbook#15]
Based on hidden_size and num_layers the flop calcuation is baseless .I feel like it is mapping a certain value to a certain number just like permutations and combinations. 
i want to calculate this for llm's based on the model chosen atleast some appropriately!!

**Comment by Quentin-Anthony** [comment]
This makes no sense to me. Can you clarify your question?

**Comment by Akash08naik** [comment]
see as we give the number of layers and hidden_size as arguments it is just running in seconds and giving us a number as flops . So how do you say that it is correct is my doubt.

 And also i need latency of the model but flops is not the same thing as when given to gpu parallel computing is also present.

**Comment by Quentin-Anthony** [comment]
We aren't calculating throughput. We're calculating the total number of floating point operations required to train/infer a model on a given number of tokens.
