### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by Akash08naik** [EleutherAI/cookbook#16]
so to benchmark llm's with huge number of parameters we need to have the file locally so as to pass it as hostfile.
Is there any other way so it can fetch automatically from hugging face and give predict the latency?

**Comment by Quentin-Anthony** [comment]
For a rough estimation, one could calculate the FLOP-seconds required to calculate a forward pass of the target HF model, then divide by the FLOPs your local GPU can realistically achieve with the target inference framework. 

We don't have functionality to provide realistic GPU FLOPs heuristics so I recommend just using https://github.com/EleutherAI/cookbook/blob/main/calc/calc_transformer_flops.py for the forward pass FLOPs and going from there.
